config/routes.rb
Appointer::Application.routes.draw do
  

  get("/dashboard", {:controller => "Dashboards", :action => "dashboard" })

  

  resources :businesses do
    resources :appointment_slots
    resources :products
    resources :gallery_images
    resources :appointment_types
  end

  devise_for :users, :controllers => { :registrations => "registrations", omniauth_callbacks: "omniauth_callbacks" }
  resources :users

  root :to => 'dashboards#dashboard'

end

app/controllers/businesses_controller.rb
class BusinessesController < ApplicationController
  before_filter :authenticate_user!
  # GET /businesses
  # GET /businesses.json
  def index
    @businesses = Business.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @businesses }
    end
  end

  # GET /businesses/1
  # GET /businesses/1.json
  def show
    @business = Business.find(params[:id])
    @appointment_slot = @business.appointment_slots.build(params[:event])
    @gallery_image = @business.gallery_images.build(params[:gallery_image])
    

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @business }
    end
  end

  # GET /businesses/new
  # GET /businesses/new.json
  def new
    @business = Business.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @business }
    end
  end

  # GET /businesses/1/edit
  def edit
    @business = Business.find(params[:id])
  end

  # POST /businesses
  # POST /businesses.json
  def create
    @business = current_user.businesses.build(params[:business])

    respond_to do |format|
      if @business.save
        format.html { redirect_to @business, notice: 'Business was successfully created.' }
        format.json { render json: @business, status: :created, location: @business }
      else
        format.html { render action: "new" }
        format.json { render json: @business.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /businesses/1
  # PUT /businesses/1.json
  def update
    @business = Business.find(params[:id])

    respond_to do |format|
      if @business.update_attributes(params[:business])
        format.html { redirect_to @business, notice: 'Business was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @business.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /businesses/1
  # DELETE /businesses/1.json
  def destroy
    @business = Business.find(params[:id])
    @business.destroy

    respond_to do |format|
      format.html { redirect_to businesses_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/businesses_helper.rb
module BusinessesHelper
end

app/views/businesses/_form.html.erb
<%= form_for(@business) do |f| %>
  <% if @business.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@business.errors.count, "error") %> prohibited this business from being saved:</h2>

      <ul>
      <% @business.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :open_time %><br />
    <%= f.time_select :open_time, :ampm => true %>
  </div>
  <div class="field">
    <%= f.label :close_time %><br />
    <%= f.time_select :close_time, :ampm => true %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/businesses/_open_close_times.html.erb
<div class="field">
    <%= f.label :open_time %><br />
    <%= f.date_select :open_time %>
  </div>
  <div class="field">
    <%= f.label :close_time %><br />
    <%= f.date_select :close_time %>
  </div>

app/views/businesses/edit.html.erb
<h1>Editing business</h1>

<%= render 'form' %>

<%= link_to 'Show', @business %> |
<%= link_to 'Back', businesses_path %>

app/views/businesses/index.html.erb
<h1>Listing businesses</h1>

<table>
  <tr>
    <th>User</th>
    <th>Name</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @businesses.each do |business| %>
  <tr>
    <td><%= business.user_id %></td>
    <td><%= business.name %></td>
    <td><%= business.description %></td>
    <td><%= link_to 'Show', business %></td>
    <td><%= link_to 'Edit', edit_business_path(business) %></td>
    <td><%= link_to 'Destroy', business, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Business', new_business_path %>

app/views/businesses/new.html.erb
<h1>New business</h1>

<%= render 'form' %>

<%= link_to 'Back', businesses_path %>

app/views/businesses/show.html.erb
<h2>Things To Do:</h2>
<ul>
  <li>Event type creation</li>
  <li>Users should only be able to select times available</li>
  
</ul>
<ul>
<li><%= link_to "Add Product", new_business_product_path(@business) %></li>
</ul>
<p>
  <b>User:</b>
  <%= @business.user_id %>
</p>

<p>
  <b>Name:</b>
  <%= @business.name %>
</p>

<p>
  <b>Description:</b>
  <%= @business.description %>
</p>


<%= link_to 'Edit', edit_business_path(@business) %> |
<%= link_to 'Back', businesses_path %> |
<%= link_to 'New Appointment', new_business_appointment_slot_path(@business) %> |
<%= link_to 'Gallery', business_gallery_images_path(@business) %> |
<%= link_to 'Types of Appointments', business_appointment_types_path(@business) %> |
<% if current_user.id = @business.user_id %>
  <%= link_to 'Add New Image', new_business_gallery_image_path(@business) %> |
  <%= link_to 'Add Appointment Type', new_business_appointment_type_path(@business) %>
<% end %>