config/routes.rb
Appointer::Application.routes.draw do
  

  get("/dashboard", {:controller => "Dashboards", :action => "dashboard" })

  

  resources :businesses do
    resources :appointment_slots
    resources :products
    resources :gallery_images
    resources :appointment_types
  end

  devise_for :users, :controllers => { :registrations => "registrations", omniauth_callbacks: "omniauth_callbacks" }
  resources :users

  root :to => 'dashboards#dashboard'

end

app/controllers/appointment_types_controller.rb
class AppointmentTypesController < ApplicationController
  # GET /appointment_types
  # GET /appointment_types.json
  def index
    @business = Business.find(params[:business_id])
    @appointment_types = @business.appointment_types.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @appointment_types }
    end
  end

  # GET /appointment_types/1
  # GET /appointment_types/1.json
  def show
    @appointment_type = AppointmentType.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @appointment_type }
    end
  end

  # GET /appointment_types/new
  # GET /appointment_types/new.json
  def new
    @business = Business.find(params[:business_id])
    @appointment_type = AppointmentType.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @appointment_type }
    end
  end

  # GET /appointment_types/1/edit
  def edit
    @appointment_type = AppointmentType.find(params[:id])
  end

  # POST /appointment_types
  # POST /appointment_types.json
  def create
    @appointment_type = AppointmentType.new(params[:appointment_type])
    @appointment_type.business_id = params[:business_id]

    respond_to do |format|
      if @appointment_type.save
        format.html { redirect_to @appointment_type.business, notice: 'appointment type was successfully created.' }
        format.json { render json: @appointment_type.business, status: :created, location: @appointment_type }
      else
        format.html { render action: "new" }
        format.json { render json: @appointment_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /appointment_types/1
  # PUT /appointment_types/1.json
  def update
    @appointment_type = AppointmentType.find(params[:id])

    respond_to do |format|
      if @appointment_type.update_attributes(params[:appointment_type])
        format.html { redirect_to @appointment_type, notice: 'appointment type was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @appointment_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /appointment_types/1
  # DELETE /appointment_types/1.json
  def destroy
    @appointment_type = AppointmentType.find(params[:id])
    @appointment_type.destroy

    respond_to do |format|
      format.html { redirect_to :back }
      format.json { head :no_content }
    end
  end
end

app/helpers/appointment_types_helper.rb
module AppointmentTypesHelper
end

app/views/appointment_types/_form.html.erb
<%= form_for([@business, @appointment_type]) do |f| %>
  <% if @appointment_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@appointment_type.errors.count, "error") %> prohibited this appointment_type from being saved:</h2>

      <ul>
      <% @appointment_type.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :business_id %>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  
  <div class="field">
    <%= f.label :duration %><br />
    <%= f.number_field :duration %> min.
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/appointment_types/edit.html.erb
<h1>Editing Appointment Type</h1>

<%= render 'form' %>

<%= link_to 'Show', @appointment_type %> |
<%= link_to 'Back', :back %>

app/views/appointment_types/index.html.erb
<h1>Listing Appointment Types</h1>

<table>
  <tr>
    <th>Business</th>
    <th>Title</th>
    <th>Duration</th>
    <th></th>
    <th></th>
  </tr>

<% @appointment_types.each do |appointment_type| %>
  <tr>
    <td><%= appointment_type.title %></td>
    <td><%= appointment_type.business_id %></td>
    <td><%= appointment_type.duration %></td>
    <td><%= link_to 'Show', business_appointment_type_path(@business, appointment_type) %></td>
    <td><%= link_to 'Edit', edit_business_appointment_type_path(@business, appointment_type) %></td>
    <td><%= link_to 'Destroy', business_appointment_type_path(@business, appointment_type), method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New appointment Type', new_business_appointment_type_path %>
<%= link_to 'Back', :back %>

app/views/appointment_types/new.html.erb
<h1>New Appointment Type</h1>

<%= render 'form' %>

<%= link_to 'Back', :back %>

app/views/appointment_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @appointment_type.title %>
</p>

<p>
  <b>Business:</b>
  <%= @appointment_type.business_id %>
</p>

<p>
  <b>Duration:</b>
  <%= @appointment_type.duration %>
</p>


<%= link_to 'Edit', edit_business_appointment_type_path(@appointment_type) %> |
<%= link_to 'Back', appointment_types_path %>