config/routes.rb
Appointer::Application.routes.draw do
  

  get("/dashboard", {:controller => "Dashboards", :action => "dashboard" })

  

  resources :businesses do
    resources :appointment_slots
    resources :products
    resources :gallery_images
    resources :appointment_types
  end

  devise_for :users, :controllers => { :registrations => "registrations", omniauth_callbacks: "omniauth_callbacks" }
  resources :users

  root :to => 'dashboards#dashboard'

end

app/models/gallery_image.rb
class GalleryImage < ActiveRecord::Base
  validates :business_id, :caption, :image, :presence => true

  attr_accessible :business_id, :caption, :image

  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }

  belongs_to :business
end

app/controllers/gallery_images_controller.rb
class GalleryImagesController < ApplicationController
  # GET /gallery_images
  # GET /gallery_images.json
  def index
    @business = Business.find(params[:business_id])
    @gallery_images = @business.gallery_images.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @gallery_images }
    end
  end

  # GET /gallery_images/1
  # GET /gallery_images/1.json
  def show
    @gallery_image = GalleryImage.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @gallery_image }
    end
  end

  # GET /gallery_images/new
  # GET /gallery_images/new.json
  def new
    @business = Business.find(params[:business_id])
    @gallery_image = GalleryImage.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @gallery_image }
    end
  end

  # GET /gallery_images/1/edit
  def edit
    @gallery_image = GalleryImage.find(params[:id])
  end

  # POST /gallery_images
  # POST /gallery_images.json
  def create
    @gallery_image = GalleryImage.new(params[:gallery_image])
    @gallery_image.business_id = params[:business_id]
    respond_to do |format|
      if @gallery_image.save
        format.html { redirect_to @gallery_image.business, notice: 'Gallery image was successfully created.' }
        format.json { render json: @gallery_image, status: :created, location: @gallery_image }
      else
        format.html { render action: "new" }
        format.json { render json: @gallery_image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /gallery_images/1
  # PUT /gallery_images/1.json
  def update
    @gallery_image = GalleryImage.find(params[:id])

    respond_to do |format|
      if @gallery_image.update_attributes(params[:gallery_image])
        format.html { redirect_to @gallery_image, notice: 'Gallery image was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @gallery_image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gallery_images/1
  # DELETE /gallery_images/1.json
  def destroy
    @gallery_image = GalleryImage.find(params[:id])
    @gallery_image.destroy

    respond_to do |format|
      format.html { redirect_to gallery_images_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/gallery_images_helper.rb
module GalleryImagesHelper
end

app/views/gallery_images/_form.html.erb
<%= form_for ([@business, @gallery_image]) do |f| %>
  <% if @gallery_image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@gallery_image.errors.count, "error") %> prohibited this gallery_image from being saved:</h2>

      <ul>
      <% @gallery_image.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.hidden_field :business_id %>
  <div class="field">
    <%= f.label :image %>
    <%= f.file_field :image %>
  </div>
  <div class="field">
    <%= f.label :caption %><br />
    <%= f.text_field :caption %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/gallery_images/edit.html.erb
<h1>Editing gallery_image</h1>

<%= render 'form' %>

<%= link_to 'Show', @gallery_image %> |
<%= link_to 'Back', :back %>

app/views/gallery_images/index.html.erb
<h1>Listing Images</h1>

<table>
  <tr>
    <th>Business</th>
    <th>Caption</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @gallery_images.each do |gallery_image| %>
  <tr>
    <td><%= image_tag(gallery_image.image(:thumb)) %></td>
    <td><%= gallery_image.business_id %></td>
    <td><%= gallery_image.caption %></td>
    <td><%= link_to 'Show', business_gallery_image_path(@business, gallery_image) %></td>
    <td><%= link_to 'Edit', edit_business_gallery_image_path(@business, gallery_image) %></td>
    <td><%= link_to 'Destroy', business_gallery_image_path(@business, gallery_image), method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Gallery image', new_business_gallery_image_path %>
<%= link_to 'Back', :back %>

app/views/gallery_images/new.html.erb
<h1>New gallery_image</h1>

<%= render 'form' %>

<%= link_to 'Back', :back %>

app/views/gallery_images/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Business:</b>
  <%= @gallery_image.business_id %>
</p>

<p>
  <b>Caption:</b>
  <%= @gallery_image.caption %>
</p>


<%= link_to 'Edit', edit_business_gallery_image_path(@gallery_image) %> |
<%= link_to 'Back', :back %>